const _source = [
    "distributorid",
    "uplineid",
    "titlecode",
    "firstname",
    "lastname",
    "dob",
    "address1",
    "address2",
    "countrycode",
    "stateid",
    "cityid",
    "pincode",
    "primaryphone",
    "displaytitle",
    "secondaryphone",
    "primarymobile",
    "emailid",
    "status",
    "regdate",
    "activationdate",
    "locationcode",
    "totalpv",
    "hiearchyid",
    "pannumber",
    "ifsccode",
    "accountno",
    "bankname",
    "gst",
    "createdby",
    "createddate",
    "updatedate",
    "updateby",
    "countryname",
    "statename",
    "cityname",
    "uplinename",
    "distsource",
    "gender",
    "dafreceived",
    "kyc",
    "firstinvoice",
    "password",
    "inttoken",
    "exttoken",
    "physicalform",
    // "udf1",
    // "udf2",
    // "udf3",
    // "udf4",
    // "udf5",
    "invoiceno",
    "branch",
    "twitter_id",
    "google_id",
    "facebook_user_name",
    "linkedin_id",
    "codistributortitlecode",
    "codistributortitle",
    "codistributorname",
    "codistributordob",
    "primarynominee",
    "secondarynominee",
    "thirdnominee",
    "primarynomineerelation",
    "secondnomineerelation",
    "thirdnomineerelation",
    "primarynomineeshare",
    "secondnomineeshare",
    "thirdnomineeshare",
    "primarynomineedob",
    "secondarynomineedob",
    "thirdnomineedob",
    "permanentlevel",
    "prevcummulativepv",
    "prevcummulativebv",
    "bonuspercent",
    // "otpmobile",
    // "otp",
    "mobileconfirmedon",
    "firstlogin",
    "ishousefundachiever",
    "iscarfundachiever",
    "isambasdor",
    "ambasdorgroup",
    "esmergeflag",
    "syncToESDate",
    // "sourceDB",
]


module.exports = {
    _source
}